name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pyinstaller build
        
    - name: Build Python package
      run: |
        python -m build
        
    - name: Test package installation
      run: |
        pip install dist/*.whl
        
    - name: Build executable
      run: |
        pyinstaller binance-mcp-server.spec
        
    - name: Test executable
      run: |
        .\dist\binance-mcp-server.exe --help || echo "Executable built successfully"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          dist/
          build/
